### ISSUE TITLE
Crash if useGpu=true in MoveNet sample

### ISSUE THREAD

**Issue by HyundongHwang** [asus4/tf-lite-unity-sample#184]
Hello.
Thanks to asus4 for working on a very nice project in Unity.
Based on this project, I am going to do pose estimation in Android using MoveNet.
I was able to run the MoveNet sample by connecting it to the Index, and I could see that the performance was very slow.
So I enabled useGpu to use GpuDelegate.
I was unable to proceed due to the following crash.

```
01-13 17:11:26.083 28233 28722 E CRASH   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-13 17:11:26.083 28233 28722 E CRASH   : Version '2021.2.7f1 (6bd9e232123f)', Build type 'Development', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
01-13 17:11:26.083 28233 28722 E CRASH   : Build fingerprint: 'samsung/b2qksx/b2q:11/RP1A.200720.012/F711NKSU2AUJ7:user/release-keys'
01-13 17:11:26.083 28233 28722 E CRASH   : Revision: '8'
01-13 17:11:26.083 28233 28722 E CRASH   : ABI: 'arm64'
01-13 17:11:26.083 28233 28722 E CRASH   : Timestamp: 2022-01-13 17:11:26+0900
01-13 17:11:26.083 28233 28722 E CRASH   : pid: 28233, tid: 28722, name: UnityMain  >>> com.DefaultCompany.MyUnityTfliteTest <<<
01-13 17:11:26.083 28233 28722 E CRASH   : uid: 10413
01-13 17:11:26.083 28233 28722 E CRASH   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
01-13 17:11:26.083 28233 28722 E CRASH   :     x0  0000000000000000  x1  0000000000007032  x2  0000000000000006  x3  00000078710d1020
01-13 17:11:26.083 28233 28722 E CRASH   :     x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  0000000000000030
01-13 17:11:26.083 28233 28722 E CRASH   :     x8  00000000000000f0  x9  dee470dbc0473d06  x10 0000000000000000  x11 ffffffc0fffffbdf
01-13 17:11:26.083 28233 28722 E CRASH   :     x12 0000000000000001  x13 00002e4c76322ef4  x14 0004695813957d76  x15 0000000034155555
01-13 17:11:26.083 28233 28722 E CRASH   :     x16 0000007bdac06c80  x17 0000007bdabe64c0  x18 00000077c103c848  x19 0000000000006e49
01-13 17:11:26.083 28233 28722 E CRASH   :     x20 0000000000007032  x21 00000000ffffffff  x22 000000787911e2bc  x23 0000007878df25a8
01-13 17:11:26.083 28233 28722 E CRASH   :     x24 0000007878e3ed80  x25 0000000000000000  x26 0000007878df42f8  x27 0000007878df4308
01-13 17:11:26.083 28233 28722 E CRASH   :     x28 0000007878df3378  x29 00000078710d10a0
01-13 17:11:26.083 28233 28722 E CRASH   :     sp  00000078710d1000  lr  0000007bdab95ef8  pc  0000007bdab95f24
01-13 17:11:26.083 28233 28722 E CRASH   : backtrace:
01-13 17:11:26.083 28233 28722 E CRASH   :       #00 pc 000000000004ef24  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: f73d1ec97729b892b1be4d71a1009def)
01-13 17:11:26.083 28233 28722 E CRASH   :       #01 pc 0000000000063ee8  /apex/com.android.runtime/lib64/bionic/libc.so (getauxval) (BuildId: f73d1ec97729b892b1be4d71a1009def)
01-13 17:11:26.083 28233 28722 E CRASH   :       #02 pc 0000000000de710c  /data/app/~~1ShXo0IoKterWup1pYTomg==/com.DefaultCompany.MyUnityTfliteTest--hUx0VHTnVsiMwEF0Ms0aQ==/lib/arm64/libil2cpp.so (BuildId: 0d52971aade79e89faf8bb0d842da12719e3b267)
01-13 17:11:26.186 28233 28722 E CRASH   : Tombstone written to: /storage/emulated/0/Android/data/com.DefaultCompany.MyUnityTfliteTest/files/tombstone_00
01-13 17:11:26.187 28233 28722 E AndroidRuntime: FATAL EXCEPTION: UnityMain
01-13 17:11:26.187 28233 28722 E AndroidRuntime: Process: com.DefaultCompany.MyUnityTfliteTest, PID: 28233
01-13 17:11:26.187 28233 28722 E AndroidRuntime: java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-13 17:11:26.187 28233 28722 E AndroidRuntime: Version '2021.2.7f1 (6bd9e232123f)', Build type 'Development', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
01-13 17:11:26.187 28233 28722 E AndroidRuntime: Build fingerprint: 'samsung/b2qksx/b2q:11/RP1A.200720.012/F711NKSU2AUJ7:user/release-keys'
01-13 17:11:26.187 28233 28722 E AndroidRuntime: Revision: '8'
01-13 17:11:26.187 28233 28722 E AndroidRuntime: ABI: 'arm64'
01-13 17:11:26.187 28233 28722 E AndroidRuntime: Timestamp: 2022-01-13 17:11:26+0900
01-13 17:11:26.187 28233 28722 E AndroidRuntime: pid: 28233, tid: 28722, name: UnityMain  >>> com.DefaultCompany.MyUnityTfliteTest <<<
01-13 17:11:26.187 28233 28722 E AndroidRuntime: uid: 10413
01-13 17:11:26.187 28233 28722 E AndroidRuntime: signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
01-13 17:11:26.187 28233 28722 E AndroidRuntime:     x0  0000000000000000  x1  0000000000007032  x2  0000000000000006  x3  00000078710d1020
01-13 17:11:26.187 28233 28722 E AndroidRuntime:     x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  0000000000000030
01-13 17:11:26.187 28233 28722 E AndroidRuntime:     x8  00000000000000f0  x9  dee470dbc0473d06  x10 0000000000000000  x11 ffffffc0fffffbdf
01-13 17:11:26.187 28233 28722 E AndroidRuntime:     x12 0000000000000001  x13 00002e4c76322ef4  x14 0004695813957d76  x15 0000000034155555
01-13 17:11:26.187 28233 28722 E AndroidRuntime:     x16 0000007bdac06c80  x17 0000007bdabe64c0  x18 00000077c103c848  x19 0000000000006e49
01-13 17:11:26.187 28233 28722 E AndroidRuntime:     x20 0000000000007032  x21 00000000ffffffff  x22 000000787911e2bc  x23 0000007878df25a8
01-13 17:11:26.187 28233 28722 E AndroidRuntime:     x24 0000007878e3ed80  x25 0000000000000000  x26 0000007878df42f8  x27 0000007878df4308
01-13 17:11:26.187 28233 28722 E AndroidRuntime:     x28 0000007878df3378  x29 00000078710d10a0
01-13 17:11:26.187 28233 28722 E AndroidRuntime:     sp  00000078710d1000  lr  0000007bdab95ef8  pc  0000007bdab95f24
01-13 17:11:26.187 28233 28722 E AndroidRuntime:
01-13 17:11:26.187 28233 28722 E AndroidRuntime: backtrace:
01-13 17:11:26.187 28233 28722 E AndroidRuntime:       #00 pc 000000000004ef24  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: f73d1ec97729b892b1be4d71a1009def)
01-13 17:11:26.187 28233 28722 E AndroidRuntime:       #01 pc 0000000000063ee8  /apex/com.android.runtime/lib64/bionic/libc.so (getauxval) (BuildId: f73d1ec97729b892b1be4d71a1009def)
01-13 17:11:26.187 28233 28722 E AndroidRuntime:       #02 pc 0000000000de710c  /data/app/~~1ShXo0IoKterWup1pYTomg==/com.DefaultCompany.MyUnityTfliteTest--hUx0VHTnVsiMwEF0Ms0aQ==/lib/arm64/libil2cpp.so (BuildId: 0d52971aade79e89faf8bb0d842da12719e3b267)
01-13 17:11:26.187 28233 28722 E AndroidRuntime:
01-13 17:11:26.187 28233 28722 E AndroidRuntime: 	at libc.abort(abort:164)
01-13 17:11:26.187 28233 28722 E AndroidRuntime: 	at libc.getauxval(getauxval:0)
01-13 17:11:26.187 28233 28722 E AndroidRuntime: 	at libil2cpp.0xde710c(Native Method)
```

PoseNet was able to use GpuDelegate, so performance was very fast.
Can MoveNet use GpuDelegate to increase performance like PoseNet?

**Comment by vikage** [comment]
Fixed in #187

**Comment by HyundongHwang** [comment]
hello vikage
Thanks for your interest in my problem.
#187 became merged and I tried running it again, but a crash occurred in another part.
This time, PoseNet also crashes, but I don't know the cause.
- test environment
  - PoseNet, MoveNet
  - GpuDelegate = true
  - Android 12
  - Samsung zflip3
  
```
E: pid: 24562, tid: 24614, name: UnityMain  >>> com.asus4.tfliteunitysample <<<
E: uid: 10422
E: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
E: Cause: null pointer dereference
E:     x0  0000007910493590  x1  0000007b9b4de31f  x2  0000000000000001  x3  ffffffffffffffff
E:     x4  ffffffffffffffff  x5  0000007881686159  x6  2064657461657243  x7  6c46726f736e6554
E:     x8  b991108882e24881  x9  b991108882e24881  x10 0000000000000001  x11 0000000000000000
E:     x12 2065746167656c65  x13 2e55504720726f66  x14 0000000000000010  x15 0000000000000000
E:     x16 00000077081fcda8  x17 0000007b9b4cf2a4  x18 00000077710fe138  x19 0000000000000000
E:     x20 000000780cf9e1c8  x21 0000007703654ab0  x22 000000788498ff00  x23 0000000000000001
E:     x24 000000780cfe3000  x25 0000000000000000  x26 0000007881689000  x27 00000076d0009e10
E:     x28 00000000000000a3  x29 0000007881686a90
E:     sp  0000007881686940  lr  0000000000000000  pc  0000000000000000
E: Tombstone written to: /storage/emulated/0/Android/data/com.asus4.tfliteunitysample/files/tombstone_00
```

**Comment by HyundongHwang** [comment]
hello vikage
The error persisted, so I tried to fix it myself.
Please take a look to see if there are any other problems.
#189
