### ISSUE TITLE
Undefined symbol: _TfLiteXNNPackWeightsCacheDelete

### ISSUE THREAD

**Issue by Xue-ShenID** [asus4/tf-lite-unity-sample#261]
Environment
 - OS/OS Version: 13.0.1 (22A400)
 - Source Version: master
 - Unity Version: 2021.3.12f1

Problem
When useing xcode project created by Unity to build ios,  Xcode shows Undefined symbol: _TfLiteXNNPackWeightsCacheDelete.

**Comment by asus4** [comment]
Thanks for reporting it. It reproduced on the latest LTS 2021.3.15f1 as well. It's wired, as there are no issues in the 2020 LTS.

**Comment by Macoron** [comment]
There is a temporary workaround. You can just remove XNN interpreter and any mentions of XNN from C# code of TFLite package. After that it can compile again.

**Comment by asus4** [comment]
Thank you @Macoron.
It looks like Unity 2022 LTS il2cpp is stripping some code in the .a file? I will check TensorFlow code as well

**Comment by Xue-ShenID** [comment]
> Thanks, @asus4 @Macoron

**Comment by asus4** [comment]
I'll keep this open and will check it later 👍

**Comment by asus4** [comment]
Hi @Xue-ShenID 

I fixed it at #271 without removing all XNNPack functionality. I only removed `TfLiteXNNPackDelegateWeightsCacheCreate` and `TfLiteXNNPackWeightsCacheDelete` from the code. 

Would be nice if you could test when you have time.

**Comment by nnurgle2** [comment]
I'm still getting the Undefined symbol: _TfLiteXNNPackWeightsCacheDelete after adding the code changes from #271

_TfLiteXNNPackWeightsCacheDelete gets added on build to the following h file:
.../UnityTTSExamples-master/Library/PackageCache/com.github.asus4.tflite@2.10.0/Plugins/iOS/TensorFlowLiteC.framework/Headers/xnnpack_delegate.h
